
[General]
	#Confetti Explosions Damage Players [false/true|default:false]
	damagePlayers = true
	#The %chance that any given creeper will explode into confetti  [0..100|default:100]
	#Range: 0 ~ 100
	confettiChance = 100
	#The %chance that any given creeper that explodes into confetti will play the cheer sound.  Set to 0 to disable.  [0..100|default:100]
	#Range: 0 ~ 100
	cheerChance = 0

