
#Daily Rewards (General configuration)
[General]
	#Time in minutes the players needs to be online on the server before receiving a reward for the day.
	#Range: 1 ~ 1440
	rewardTimePerDay = 30
	#Shows the rewards menu when a player joins the server (if there are unclaimed rewards).
	showRewardMenuOnPlayerJoin = false

["Fill Items"]
	#Use fill items if there are not enough valid items for a month. (e.g. if there are only 2 items for a month and the player claims 3 rewards, the 3rd reward will be a fill item)
	useFillItems = true
	#List of normal fill items which are used in the case we have not enough valid items for a month.
	normalFillItems = ["coinsje:copper_coin_pile","coinsje:copper_coin_pile:2","coinsje:copper_coin_pile:3","coinsje:copper_coin_pile:4", "coinsje:iron_coin","coinsje:iron_coin:2","coinsje:iron_coin:3","coinsje:iron_coin:4", "coinsje:iron_coin_pile","coinsje:iron_coin_pile:2", "apotheosis:common_material:32", "apotheosis:uncommon_material:16", "majruszsdifficulty:bandage:16", "majruszsdifficulty:golden_bandage:8", "seadwellers:mermorph_loot_crate:16","seadwellers:blacksmith_loot_crate:16","seadwellers:architect_loot_crate:16","seadwellers:farmer_loot_crate:16","seadwellers:hunter_loot_crate:16","seadwellers:collector_loot_crate:16","seadwellers:river_loot_crate:16","seadwellers:cavern_loot_crate:16","seadwellers:coral_loot_crate:16","seadwellers:icy_loot_crate:16", "aquaculture:box:16", "tetra:forged_bolt:4", "tetra:forged_beam:4", "tetra:metal_scrap:8", "the_bumblezone:royal_jelly_bottle:2", "magnumtorch:diamond_magnum_torch", "tombstone:grave_dust:4", "irons_spellbooks:common_ink:2", "irons_spellbooks:uncommon_ink", "skilltree:wisdom_scroll"]
	#List of rare fill items which are used in the case we have not enough valid items for a month.
	rareFillItems = ["coinsje:gold_coin", "apotheosis:rare_material:8", "apotheosis:epic_material:4", "apotheosis:mythic_material:4", "sophisticatedbackpacks:backpack", "aquaculture:lockbox:4", "aquaculture:treasure_chest:2", "tetra:chthonic_extractor", "enigmaticlegacy:astral_dust:4", "enigmaticlegacy:earth_heart", "the_bumblezone:crystalline_flower", "simplyswords:runefused_gem", "simplyswords:netherfused_gem", "tombstone:essence_of_undeath", "irons_spellbooks:legendary_ink", "irons_spellbooks:rotten_spell_book", "skilltree:amnesia_scroll"]
	#The chance to use a rare item instead of a regular one. e.g. 7 means every 7th items could be a rare item. (0 = disabled)
	#Range: 0 ~ 100
	rareFillItemsChance = 7
	#List of loot bag fill items which are used in the case we have not enough valid items for a month.
	lootBagFillItems = ["wandering_bags:wandering_bag", "wandering_bags:pillager_bag", "wandering_bags:witch_bag", "wandering_bags:piglin_bag", "wandering_bags:ancient_bag"]
	#The chance to use a loot bag item instead of a regular one. e.g. 15 means every 15th items could be a loot bag item. (0 = disabled)
	#Range: 0 ~ 100
	lootBagFillItemsChance = 15

["Rewards Items"]
	#Shuffle the rewards items instead of using the defined order.
	shuffleRewardsItems = true
	#List of rewards items for January.
	rewardsJanuaryItems = []
	#List of rewards items for February.
	rewardsFebruaryItems = []
	#List of rewards items for March.
	rewardsMarchItems = []
	#List of rewards items for April.
	rewardsAprilItems = []
	#List of rewards items for May.
	rewardsMayItems = []
	#List of rewards items for June.
	rewardsJuneItems = []
	#List of rewards items for July.
	rewardsJulyItems = []
	#List of rewards items for August.
	rewardsAugustItems = []
	#List of rewards items for September.
	rewardsSeptemberItems = []
	#List of rewards items for October.
	rewardsOctoberItems = []
	#List of rewards items for November.
	rewardsNovemberItems = []
	#List of rewards items for December.
	rewardsDecemberItems = []

