
#Daily Rewards (General configuration)
[General]
	#Time in minutes the players needs to be online on the server before receiving a reward for the day.
	#Range: 1 ~ 1440
	rewardTimePerDay = 30
	#Shows the rewards menu when a player joins the server (if there are unclaimed rewards).
	showRewardMenuOnPlayerJoin = false

["Fill Items"]
	#Use fill items if there are not enough valid items for a month. (e.g. if there are only 2 items for a month and the player claims 3 rewards, the 3rd reward will be a fill item)
	useFillItems = true
	#List of normal fill items which are used in the case we have not enough valid items for a month.
	normalFillItems = ["gobber2:gobber2_gooey_bread:4", "majruszsdifficulty:bandage:8", "minecraft:lantern:64", "minecraft:raw_iron:16", "apotheosis:common_material:32", "apotheosis:uncommon_material:16", "apotheosis:rare_material:8", "apotheosis:sigil_of_socketing", "the_bumblezone:royal_jelly_bottle", "farmingforblockheads:green_fertilizer:8", "farmingforblockheads:red_fertilizer:8", "farmingforblockheads:yellow_fertilizer:8", "thermal:upgrade_augment_1", "brewinandchewin:flaxen_cheese_wheel", "brewinandchewin:scarlet_cheese_wheel", "aquaculture:box:2", "tetra:geode:32", "sophisticatedbackpacks:backpack", "enigmaticlegacy:earth_heart", "enigmaticlegacy:astral_potato:8", "gag:mining_dynamite:32", "simplyswords:runefused_gem", "forbidden_arcanus:orb_of_temporary_flight", "minecraft:andesite:64", "ic2:coin", "ic2:coin:2", "ic2:coin:4", "ic2:coin_8x"]
	#List of rare fill items which are used in the case we have not enough valid items for a month.
	rareFillItems = ["ae2:flawless_budding_quartz:1", "minecraft:budding_amethyst:1", "apotheosis:epic_material:4", "apotheosis:mythic_material:1", "torchmaster:megatorch:2", "apotheosis:superior_sigil_of_socketing", "the_bumblezone:crystalline_flower", "thermal:upgrade_augment_2", "aquaculture:lockbox:2", "sophisticatedbackpacks:diamond_backpack", "simplyswords:netherfused_gem", "createaddition:diamond_grit_sandpaper", "minecraft:ancient_debris:4"]
	#The chance to use a rare item instead of a regular one. e.g. 7 means every 7th items could be a rare item. (0 = disabled)
	#Range: 0 ~ 100
	rareFillItemsChance = 7
	#List of loot bag fill items which are used in the case we have not enough valid items for a month.
	lootBagFillItems = ["aquaculture:treasure_chest:2", "wandering_bags:wandering_bag", "wandering_bags:pillager_bag", "wandering_bags:witch_bag", "wandering_bags:piglin_bag"]
	#The chance to use a loot bag item instead of a regular one. e.g. 15 means every 15th items could be a loot bag item. (0 = disabled)
	#Range: 0 ~ 100
	lootBagFillItemsChance = 15

["Rewards Items"]
	#Shuffle the rewards items instead of using the defined order.
	shuffleRewardsItems = true
	#List of rewards items for January.
	rewardsJanuaryItems = []
	#List of rewards items for February.
	rewardsFebruaryItems = []
	#List of rewards items for March.
	rewardsMarchItems = []
	#List of rewards items for April.
	rewardsAprilItems = []
	#List of rewards items for May.
	rewardsMayItems = []
	#List of rewards items for June.
	rewardsJuneItems = []
	#List of rewards items for July.
	rewardsJulyItems = []
	#List of rewards items for August.
	rewardsAugustItems = []
	#List of rewards items for September.
	rewardsSeptemberItems = []
	#List of rewards items for October.
	rewardsOctoberItems = []
	#List of rewards items for November.
	rewardsNovemberItems = []
	#List of rewards items for December.
	rewardsDecemberItems = []

